### ISSUE TITLE
Using this form with other components

### ISSUE THREAD

**Issue by tinyweasel** [adfinis-sygroup/ember-validated-form#21] opened 2017-03-29 10:08 UTC
Is it possible to have some form elements be a power-select and still have the form submit their values?

**Comment by czosel** [comment] 2017-04-04 15:11
I'll close this since it hope it is resolved - feel free to reopen if not.

**Closed by czosel** 2017-04-04 15:11 UTC

**Comment by tinyweasel** [comment] 2018-03-09 13:52
Many months later I'm having an issue where I've set onblur=fi.setDirty, but the problem is, if I load the form with values pre-selected, and I de-select them, it doesn't get set to dirty and I don't get the validation error until I activate the dropdown. Any ideas of a fix?

**Comment by czosel** [comment] 2018-03-09 14:19
Hi @tinyweasel!
I'm not sure if i understand the issue completely - can you try to create a reproduction in a twiddle? You could use [this one](https://ember-twiddle.com/3691a8576c35ff149bfc26a564ec5437) as a starting point.
Thanks!
