### ISSUE TITLE
Integrating with Other components

### ISSUE THREAD

**Issue by g8anusha** [adfinis-sygroup/ember-validated-form#43] opened 2017-07-07 06:03 UTC
Hi,

I am using power-select and power-select-multiple with validated-form like : 

model -> 

> {
>                   obj: {
>                            id: null,
>                            name: null
>                           }
>                }

> {{#f.input name='obj'as |fi|}}
>     {{#power-select-multiple
>        options=options
>        searchField='name'
>        onchange=fi.update
>        placeholder='Select'
>        selected obj as |o|}}
>       {{o.name}}
>     {{/power-select-multiple}}
> {{/f.input}}

With this, I am able to see the dropdown, but selecting a value doesn't render the selected value to the dropdown. Also, I am not able to search using name.

Kindly give some guidance.

Thanks in advance!

**Comment by g8anusha** [comment] 2017-07-07 06:12
Sorry a slight correction. The selected value doesn't render in the field. I am only able to view the placeholder even after selection.

**Comment by czosel** [comment] 2017-07-07 08:03
Hi @g8anusha,

thanks for your bug report! I played around with your example a little bit and realized that the only thing you were missing is the proper definition of the `selected` attribute:
```handlebars
selected=fi.value
```
I created a [twiddle](https://ember-twiddle.com/3547207b06ed896f123332dd772503d0?openFiles=templates.application.hbs%2C) with a basic example. 

Just to give some context: Passing `fi.update´ to `onchange` will update the `obj` property of our model with the currently selected value. In order for that value to be displayed, you'll have to pass it back into the select's `selected` attribute, which can be done via `fi.value` or the longer version `f.model.obj`.

Currently, we're clearly lacking documentation for this - I'll leave this issue open until we have proper docs.

Bonus: The twiddle also shows how to integrate `fi.setDirty` for proper dirty state handling!

I hope that helps! :smile:

**Comment by g8anusha** [comment] 2017-07-07 08:27
Hi, Thanks a lot for the prompt response.

But, it gives the error "newSelection.push(option) is not a function, where I get newSelection as obj"

**Comment by g8anusha** [comment] 2017-07-07 08:33
Hey, am really sorry I changed it to f.model.obj and it worked!!

Many thanks! :)

**Comment by czosel** [comment] 2017-07-11 11:29
I'll close this since we have better documentation now :smile:

**Closed by czosel** 2017-07-11 11:29 UTC

**Comment by ioleo** [comment] 2018-08-12 08:02
@czosel sorry for necromancy, but I'm trying to do exacly what this issue describes:

```
{{#validated-form
   model = (changeset model ItemValidations)
   on-submit = (perform submit)
   as |form|
}}
  <!-- ... other inputs ... -->

  {{#form.input 
     label    = "Category" 
     name     = "category"
     required = true 
     as |input|
  }}
    <!-- categories is an additional model fetched in route via this.get('store').findAll('category'), it uses ember data -->
    {{#power-select
       options     = categories
       searchField = "name"
       placeholder = "Choos category..."
       onchange    = input.update
       selected    = input.value
       onblur      = input.setDirty
       as |category|
    }}
        {{category.name}} 
    {{/power-select}}
  {{/form.input}}
  <!-- ... -->
{{/validated-form}}

**Comment by ioleo** [comment] 2018-08-12 13:40
@czosel OK, it seems I accidentally discovered the cause of the problem :joy: 

In my ROUTE I was using `this.get('store').createRecord('item')` to create an empty model for the form.
This approach has several drawbacks:
* if you enter the `/items/create` route, the empty item is immidietly added to the underlaying model, and may change some other components (eg. if I had "total items counter" somewhere, it would be immidietly incremented)
* if you exit the `/items/create` route, the empty item stays in the storage (even though it was never saved), you have to explicitly unload the item in `deactivate` hook
* when I called `save()` on item, I was getting `Assertion Failed: item was saved to the server, but the response returned the new id '71', which has already been used with another record.'"` which resulted in two identical items in the store, except one did not have id (and also required additional handling)

Now for these reasons, I've changed my approach, and I use `EmberObject.create({})` as my form model, and will do `store.createRecord` only when submiting valid form.

To my surprise, suddently power-select works as expected :) So it seems the issue was with the way Ember data proxies its objects.

**Comment by czosel** [comment] 2018-08-12 16:41
Hi @ioleo, I'm glad you were able to resolve the issue! I don't think I've run into it before myself, probably because I'm always calling `createRecord` when the form is submitted for the same reasons you outlined above.
